baseURL = "https://agilewarsaw.com/"
languageCode = "en-us"
title = "Agile Warsaw"

theme = ["agilewarsaw"]
buildFuture = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = -100

  [[menu.main]]
    identifier = "archive"
    name = "All events"
    url = "/events"
    weight = 1

  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "https://faq.agilewarsaw.com"
    weight = 1