publishDir: docs
baseurl: "https://abelight.agilewarsaw.com"
title: "ABE Light 2022"
canonifyurls: true
theme: "hugo-conference"

#GoogleAnalytics: "UA-112461830-1"

params:
  # Conference info
  Name: "ABE Light 2022"
  Description: "AgileByExample Light 2022"
  Date: "4 June (Saturday)"
  startDate: "2022-06-04T13:45"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: " Akademia Finansów i Biznesu Vistula"
  Address: "Stokłosy 3"
  City:  "Warsaw"
  #State: "Quintana"
  Images: ["/img/ABElight-ikonka.png"]

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - partners
    - sponsors
    - media
    - orgs
    - previous
      #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About the conference"
    location: "Where?"
    speakers: "Who?"
    schedule: "Timetable"
    sponsors: "Sponsors"
    partners: "Partners"
    media: "Media Partners"
    orgs: "Organizers"
    contact: "Contact"
    previous: "Previous Editions"

  Previous:
    - name: "2013"
      url: "https://agilewarsaw.com/events/55/"
    - name: "2014"
      url: "https://agilewarsaw.com/events/78/"
    - name: "2015"
      url: "https://agilewarsaw.com/events/98/"
    - name: "2016"
      url: "https://agilewarsaw.com/events/115/"
    - name: "2017"
      url: "https://agilewarsaw.com/events/130/"
    - name: "2018"
      url: "https://agilewarsaw.com/events/150/"
    - name: "2019"
      url: "https://agilewarsaw.com/events/179/"
    - name: "2020"
      url: "https://agilewarsaw.com/events/198/"
    - name: "2021"
      url: "https://agilewarsaw.com/events/228/"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
     text: "Free Registration"
     link: "register"
      #text: "Zarejestruj się gratis"
      #link: "register"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
      #- name: "KMD"
      #logo: "img/logo_kmd.png"
      #url: "https://career.kmd.net/join-kmd-poland"

    - name: "ProCognita"
      logo: "img/logo_procognita.png"
      url: "https://procognita.pl/"

      #  - name: "Vistula"
      #    logo: "img/logo_vistula.jpg"
      #    url: "http://www.vistula.edu.pl/"

      #- name: "Slido"
      #logo: "img/logo_slido.png"
      #url: "http://www.slido.com"

  # List of Partners
  Partners:
    - name: "Agile Warsaw"
      logo: "img/logo_AW.png"
      url: "http://agilewarsaw.com"

      # - name: "PKO BP"
      #   logo: "img/logo_PKOBP.jpg"
      #   url: "https://www.pkobp.pl"

      #- name: "PMI Oddział Warszawa"
      #logo: "img/logo_PMI.png"
      #url: "http://pmi.org.pl/pmi/oddzialy/warszawa/"

  # List of Media Partners
  Media:
      - name: "Agile Polska"
        logo: "img/logo_APL.png" 
        url: "http://agilepolska.pl/"

      #- name: "Agile 247"
      #logo: "img/logo_a247.jpg" 
      #url: "http://www.agile247.pl/"

      #- name: "Agile 4U"
      #logo: "img/logo_agile4u.png" 
      #url: "https://www.meetup.com/agile4u/"

      #- name: "Big Agile Theory"
      #logo: "img/logo_big-agile-theory.png" 
      #url: "https://www.meetup.com/Big-Agile-Theory/"

      #- name: "Fundacja Zwinność"
      #logo: "img/logo_fundacja-zwinnosc.jpg" 
      #url: "https://zwinnosc.org/"
      
      #- name: "LubLean"
      #logo: "img/logo_LubLean.png" 
      #url: "https://www.meetup.com/LubLean-and-Agile/"
      
      #- name: "Agile Poznań"
      #logo: "img/logo_ap_margines.png" 
      #url: "https://agilepoznan.org/"

      #- name: "Kanban przy kawie"
      #logo: "img/logo_kanban_przy_kawie.png" 
      #url: "https://kanbanprzykawie.pl/"


  Orgs:
    - name: "Piotr Radaj"
      img: "img/org_radaj.png"
    - name: "Ania Przybyszewska"
      img: "img/org_przybyszewska.png"
    - name: "Łukasz Przezorski"
      img: "img/org_przezorski.png"
    - name: "Kinga Grabowska"
      img: "img/org_kinga.png"
    - name: "Mateusz Srebrny"
      img: "img/org_srebrny.png"
    # - name: "Magdalena Walczak"
    #img: "img/org_walczak.png"
    - name: "Łukasz Szóstek"
      img: "img/org_szostek.png"
    - name: "Ewa Koprowska"
      img: "img/org_koprowska.png"
      #- name: "Piotr Szczygieł"
      #img: "img/org_szczygiel.png"

  # The entire schedule
  Schedule:
    - name: "Opening"
      time: "13h45"
      remark: "Please, be on time!<br>This is where you will be signing-up for workshops."

    - authors:
        - name: "Paul Klipp"
          photo: "img/klipp.jpg"
          bio: "Paul is a coach who works with leaders and organizations to instil lean and agile thinking and practices that improve product development and delivery. He is the founder of Lunar Logic and the ACE! Conference. He is also co-host of the Agile Book Club podcast."
          link:
            href: "https://paulklipp.com/"
            text: www
      presentation:
        title: "The title is still under construction…"
        description: "Paul is creating this talk especailly for this conference :) <br>About continuous learning, a deep dive into product culture and psychological safety. <img class=\"icon-lang\" src=\"img/lang-gb.svg\">"

    - authors:
        - name: "Bartosz Janowski"
          photo: "img/janowski.jpg"
          #bio: "bio"
          #link:
            #href: "https://www.linkedin.com/in/paulklipp/"
            #text: LinkedIn
      presentation:
        title: "Coś wokół: \"Za co płacą scrum masterowi?\""
        description: "tbd <img class=\"icon-lang\" src=\"img/lang-pl.svg\">"

    - authors:
        - name: "Maciej Malesa"
          photo: "img/malesa.jpg"
          #bio: "bio"
          #link:
            #href: "https://www.linkedin.com/in/paulklipp/"
            #text: LinkedIn
      presentation:
        title: "Przykład samoorganizującego się zespołu i kilku wyzwań którym sprostał"
        description: "tbd <img class=\"icon-lang\" src=\"img/lang-pl.svg\">"


    - name: "Parallel Workshops"
      #time: "14h15"
      remark: "The workshops will be held in parallel.<br>
      Workshop languages are mentioned in descriptions.<br><br>
      
      <strong>Justyna Rędzikowska<br>
      Jak się za to zabrać? Czyli o przełożeniu teorii metryk do pierwszego, konkretnego użycia w zespole</strong>
      <img class=\"icon-lang\" src=\"img/lang-pl.svg\"> <br>
      Jest to warsztat dla:<br>
      <ul style=\"padding-left: 0.5em;\">
<li>• takiej mnie sprzed kilku lat, czyli każdej osoby, która chce zacząć pracę z metrykami, a do tego zaangażować w to cały zespół,</li>
<li>• każdej osoby, która chce opierać pracę z procesem na danych i mieć porządny wkład do Retrospektywy,</li>
<li>• każdej osoby, która wie o istotności metryk, ale zawsze ciężko było jej zacząć, bo nie wiedziała w szczegółach od czego i jak.</li>
</ul>
Z faktu, że pełnię rolę Scrum Masterki, to skupię się na metrykach procesowych (nie produktowych). Niemniej wartość z tego warsztatu będzie płynęła dla każdej osoby zainteresowanej pracą z danymi w zespole Scrumowym. Jako FRISowy Badacz z Partnerskim zacięciem - zapraszam na naszą małą przygodę z budowaniem zespołu wykresów :)

      <br><br>"


      #- name: "Closing"
        #remark: ""

    - name: "Afterparty!"

    #- name: "Lunch"
      #remark: "You will have to take care of your own lunch. There are restauriants in the neighbourhood."



     ###########################
     ###  WORKSHOP TRAINERS  ###
     ###########################

    - authors:
        - name: "Justyna Rędzikowska"
          photo: "img/redzikowska.png"
          bio: "Buduję zespoły, pracuję z wartościami, ludźmi, danymi i procesami. Uwielbiam się uczyć oraz dzielić wiedzą. Od 2003 rozwijam się jako liderka, a od 2006 jako trenerka, facylitatorka i mentorka. Lubię zadawać pytania, ogromnie ciekawi mnie świat, człowiek i procesy jakie zachodzą pomiędzy. W 2018 odkryłam Scrum i Agile, a od 2019 jestem pełnoetatową Scrum Masterką i uwielbiam swoją pracę. Aktualnie działam jako Scrum Masterka w BinarApps, w mojej ukochanej Łodzi."
          link:
              href: "https://www.linkedin.com/in/justyna-redzikowska/"
              text: "LinkedIn"
          # presentation: "title"
          # description: "desc"
      workshop: true


    #####################
    ##     TEMPLATE    ##
    #####################
      # DWÓCH PRELEGENTÓW WYGLĄDA TAK:
      #    - authors:
      #        - name: "Hanna Kaczyńska"
      #          photo: "img/kaczynska.jpg"
      #          bio: "W PKO BP od 10 lat. Początki to obsługa klienta i sprzedaż, od 7 lat zajmuję się projektowaniem i prowadzeniem szkoleń w banku. Ponad rok temu zetknęłam się po raz pierwszy ze zwinnością, dziś sama nią zarażam jako Scrum Master i jako trener prowadzący szkolenia dla organizacji. Uwielbiam pracę z ludźmi i dla ludzi."
      #          link:
      #            href: "https://pl.linkedin.com/in/hanna-kaczyńska-508960142"
      #            text: "LinkedIn"
      #        - name: "Karol Krawiec"
      #          photo: "img/krawiec.jpg"
      #          bio: "Z sektorem bankowym związany od 15 lat, zaczynał swoje doświadczenie jako programista COBOL i konsultant w tworzeniu centralnego systemu bankowego. Kierował różnorodnymi projektami i programami IT dot. rozwoju produktów i usług bankowych, zarządzał zespołem Kierowników Projektów. Zainspirowany dążeniem ku zwinności, z pasją adaptuje podejście Agile – najpierw w zespołach IT, obecnie w ramach Transformacji Cyfrowej w skali całej Organizacji. Scrum Master, Product Owner i wyznawca idei ‘Da Się’."
      #          link:
      #            href: "https://pl.linkedin.com/in/karolkrawiec"
      #            text: "LinkedIn"
      #      presentation:
      #        title: "Dlaczego (czasem) warto zdjąć miarę u krawca?"
      #        description: "Rynek szkoleń pełen jest gotowych rozwiązań, które pozwalają zdobywać czy rozwijać potrzebne w organizacji kompetencje. Trudno jednak w komercyjnych propozycjach znaleźć zgrabny pakiet uszyty na miarę dla konkretnej firmy. Ustalone pół roku wcześniej z firmą szkoleniową programy szybko się dezaktualizują i nie zawsze elastycznie się negocjują. Kiedy do tego wszystkiego dodamy nowe w organizacji role: Product Owner i Scrum Master oraz założymy, że organizacja chce inwestować w ich rozwój - zapotrzebowanie ilościowe i jakościowe na różne szkolenia rośnie...
      #Jak firma może poradzić sobie z tym wyzwaniem? I dlaczego, zamiast kupować gotowe ubrania ze sklepowych wieszaków, czasem warto mieć firmowego krawca, który zawsze zdejmie z nas właściwą miarę?<br>Zapraszamy do wysłuchania opowieści o pewnej Akademii Zwinności…"

