publishDir: docs
baseurl: "https://abelight-2018.agilewarsaw.com"
title: "ABE Light 2018"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "UA-112461830-1"

params:
  # Conference info
  Name: "ABE Light 2018"
  Description: "Konferencja Agile by Example Light 2018"
  Date: "17 marca (sobota)"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Akademia Finansów i Biznesu VISTULA"
  Address: "Stokłosy 3"
  City:  "Warszawa"
  #State: "Quintana"
  Images: ["/img/ABElight-ikonka.png"]

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - sponsors
    - partners
    - media
    - orgs
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "O konferencji"
    location: "Gdzie?"
    speakers: "Kto?"
    schedule: "Rozkład jazdy"
    sponsors: "Sponsorzy"
    partners: "Partnerzy"
    media: "Partnerzy medialni"
    orgs: "Organizatorzy"
    contact: "Kontakt"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
      text: "Zarejestruj się gratis"
      link: "register"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "ProCognita"
      logo: "img/logo_procognita.png"
      url: "https://procognita.pl/"

    - name: "AZA"
      logo: "img/aza_logo_graphite_box.png"
      url: "https://azagroup.eu/o-nas/"

    - name: "Vistula"
      logo: "img/logo_vistula.jpg"
      url: "http://www.vistula.edu.pl/"

    - name: "Slido"
      logo: "img/logo_slido.jpg"
      url: "http://www.slido.com/"

  # List of Partners
  Partners:
    - name: "Agile Warsaw"
      logo: "img/logo_AW.png"
      url: "http://agilewarsaw.com"

    - name: "PMI Oddział Warszawa"
      logo: "img/logo_PMI.png"
      url: "http://pmi.org.pl/pmi/oddzialy/warszawa/"

  # List of Media Partners
  Media:
    - name: "Agile Polska"
      logo: "img/logo_APL.png" 
      url: "http://agilepolska.pl/"

    - name: "Agile 247"
      logo: "img/logo_a247.png" 
      url: "http://www.agile247.pl/"

  Orgs:
    - name: "Ewa Koprowska"
      img: "img/org_koprowska.png"
    - name: "Piotr Radaj"
      img: "img/org_radaj.png"
    - name: "Mateusz Srebrny"
      img: "img/org_srebrny.png"
    - name: "Łukasz Szóstek"
      img: "img/org_szostek.png"
    - name: "Magdalena Walczak"
      img: "img/org_walczak.png"
    - name: "Michał Koprowski"
      img: "img/org_koprowski.png"
    - name: "Piotr Szczygieł"
      img: "img/org_szczygiel.png"

  # The entire schedule
  Schedule:
    - name: "Startujemy"
      time: "13h45"
      remark: "Bardzo prosimy przybywać na czas."

    - name: "AZA Group"
      #time: "13h45"
      remark: "Kilka słów od sponsora: ,,Młodzi i ambitni. Jak bardzo zwinni? Czyli agile w AZAGroup''."

      # - name: "AZA Group"
      # - photo: "img/aza_logo_graphite_box.png"
      # - bio: "skipThisFromSpeakers"
      # - presentation:
      # -   title: ""
      # -   description: "Krótka i zabawna prezentacja sponsora…"
      # -   #time: "11h00"

    - name: "Mary Poppendieck"
      photo: "img/mary.jpg"
      bio: "Mary Poppendieck started her career as a process control programmer, moved on to manage the IT department of a manufacturing plant, and then ended up in product development, where she was both a product champion and department manager.<br/> Mary considered retirement 1998, but instead found herself managing a government software project where she first encountered the word \"waterfall.\" When Mary compared her experience in successful software and product development to the prevailing opinions about how to manage software projects, she decided the time had come for a new paradigm. She wrote the award-winning book \"Lean Software Development: An Agile Toolkit\" in 2003 to explain how the lean principles from manufacturing offer a better approach to software development.<br/> Over the past several years, Mary has found retirement elusive as she lectures and teaches classes with her husband Tom. Based on their on-going learning, they wrote a second book, \"Implementing Lean Software Development: From Concept to Cash\" in 2006, a third, \"Leading Lean Software Development: Results are Not the Point\" in 2009, and a fourth book, \"The Lean Mindset: Ask the Right Questions\" in 2013. A popular writer and speaker, Mary continues to bring fresh perspectives to the world of software development."
      #company: "Linux Foundation"
      link:
        href: "http://www.poppendieck.com/"
        text: "www"
      presentation:
        title: "Four Metaphors for Lean"
        description: "Sometimes lean principles are easier to understand when we find them operating in completely
unexpected places. This talk will take you to marketplaces around the world, on arctic expeditions, down
whitewater rapids, and into research labs to see lean principles in action. Because sometimes the ideas
that seem so counterintuitive in our daily lives become completely obvious when the game has changed."
        #time: "14h00"

    - name: "ProCognita"
      #photo: "img/wykowski.jpg"
      photo: "img/procognita_team.jpg"
      #photo: "/img/speaker.jpg"
      bio: "Od 2010 roku wspieramy ludzi w tworzeniu uczących się organizacji i dostarczaniu niesamowitych produktów. Dzielimy się wiedzą i doświadczeniem poprzez szkolenia, mentoring, wykłady i warsztaty. Jako jedyni organizujemy szkolenia Certified ScrumMaster, Certified Scrum Product Owner i Certified LeSS Basics po polsku. Wspólnie przeszkoliliśmy ponad 2000 osób w 6 krajach na dwóch kontynentach.
      <br/>
      Współpracujemy z kilkoma międzynarodowymi organizacjami zrzeszającymi ekspertów Agile i Lean takimi jak Scrum Alliance i LeSS Company. Nasi partnerzy i przyjaciele zapewniają nam wsparcie i wiedzę, oraz szerszą perspektywę pracy z klientem. Możecie nas spotkać na międzynarodowych konferencjach i spotkaniach lokalnych społeczności Agile i Lean."
      #company: "ProCognita"
      link:
        href: "https://procognita.pl"
        text: "www"
      presentation:
        title: "Warsztat: Efektywni czy zajęci - Symulacja Lean"
        description: "Masz uczucie, że wszyscy w twojej firmie jesteście bardzo zajęci, ale rezultatów nie widać? Zapraszamy Cię na nasz warsztat, gdzie poprzez symulację zobaczymy co powoduje największe problemy tradycyjnych organizacji. Spróbujemy je też zaadresować, używając narzędzi Lean, takich jak Kanban i poszukiwanie strat. Oczywiście nasze wnioski przeniesiemy na grunt tworzenia oprogramowania, tak abyście mogli je zastosować w poniedziałek po konferencji.
<br/>
<br/>
ps. Mamy Lego i nie zawahamy się go użyć. :)"
        #time: "11h00"

    - name: "Lunch"
      remark: "Każdy płaci za siebie. Kantyna Vistuli da radę nas obsłużyć."

    - name: "Michał Dworczyk"
      photo: "img/dworczyk.jpg"
      bio: "Entuzjasta życia, projektant startupów, fotograf, aktor. Poszukiwacz rozwiązań prostych, lecz nieoczywistych. Zwolennik Deep Thinking, co lubi tłumaczyć jako myślenie o myśleniu. Od ponad dwudziestu lat jest obecny w strukturach zarządzania projektami, marketingu, reklamy i PR.<br/> Studiował w Centrum kształcenia kadr kierowniczych DOSKO na wydziale Public Relations, w Państwowej wyższej szkole Filmowej Telewizyjnej i Teatralnej w Łodzi.<br/> Jest certyfikowanym coachem International Coaching Community. no. 11488, Praktykiem Neurolingwistyki - The Society of Neuro Linguistic Programing, ukończył również kurs: Re-evaluating Life Story Certification authority Christina Hall, Ph.D., NLP Meta-Master Trainer.
<br/>
Pomaga ludziom osiągać cele, odkrywać inne sposoby widzenia świata."
#company: "firma"
      link:
        href: "https://www.linkedin.com/in/michał-dworczyk-54484221/"
        text: "LinkedIn"
      presentation:

        title: "O podglądaniu, patrzeniu, podpatrywaniu i widzeniu"
        description: "Tym razem pokażę kilka zdjęć. Opowiem o tym co w nich widzę.<br/> Dlaczego są właśnie takie jakimi je zobaczycie?<br/>  O perspektywie w fotografii i w życiu. O próbie rezygnacji z ustawień domyślnych...<br/><br/> Możliwe, że im mniej teraz napiszę, tym przyjemniej będzie Wam patrzeć i słuchać...<br/> Może tylko patrzeć, a może tylko słuchać?"

    - name: "Dorota Jaworska"
      photo: "img/jaworska.jpg"
      bio: "Project Manager/Product Owner. <br/>Pracowała w korporacjach i startupach. Z branżą IT związana od 10 lat. Fanka czarnej kawy, retrospekcji i szukania dziury w całym. <br/>Prywatnie entuzjastka małych szczeniaczków."
      #company: "firma"
      link:
        href: "https://www.linkedin.com/in/djaworska/"
        text: "LinkedIn"
      presentation:
        title: "Jak poskromić Ciemną Stronę Mocy?"
        description: "Co zrobić kiedy osoba z Twojego zespołu cierpi na depresję? Czego na pewno nie robić? Jak pomóc Twojemu współpracownikowi i zorganizować pracę zespołu aby dowozić? <br/>Wiele się mówi o depresji i o stanach lękowych, ale nikt nie przygotowuje nas, zarządzających ludźmi, do mierzenia się z takim sytuacjami w pracy. <br/>Na podstawie własnych doświadczeń i obserwacji, chcę dotknąć trudnego tematu o którym się nie mówi na głos. "

    - name: "Marcin Gozdalik"
      photo: "img/gozdalik.jpg"
      bio: "ex-CTO, ex-co-founder, obecnie konsultant w 9LivesData oraz head of engineering w Starfish Storage"
      #company: "firma"
      link:
        href: "https://www.linkedin.com/in/gozdal/"
        text: "LinkedIn"
      presentation:
        title: "Kiedy nie warto używać Continuous Integration / Continuous Delivery?"
        description: "Dawno temu (w 2000 roku!) na liście \"The Joel Test: 12 Steps to Better Code\" Joel Spolsky na pierwszym miejscu umieścił pytanie \"Do you use source control?\". Dawno nie spotkałem projektu który już tutaj odpadał i odpowiadał \"nie\", chociaż jeszcze parę lat temu takie projekty widziałem. Na trzecim miejscu było \"Do you do daily builds?\". Znam wiele projektów dzisiaj, które ciągle przy tym pytaniu odpadają. Gdyby zapytać o Continuous Integration, Deployment albo Delivery jeszcze mniej projektów będzie mogło podnieść łapkę w górę. Chciałbym opowiedzieć co pomogło nam dojść do 10 buildów dziennie w zespole siedmioosobowym i kiedy nie warto używać CI/CD."

    - name: "Afterparty"
      remark: "W pobliżu…"
      time: "~19h30"


      #    - name: "Steve Wozniak"
      #      photo: "/img/speaker.jpg"
      #      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      #      company: "Apple, Inc."
      #      link:
      #        href: "http://twitter.com/woz"
      #        text: "@woz"
      #      presentation:
      #        title: "Why do I prefer Android over iPhone"
      #        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      #        time: "17h00"
