publishDir = "docs"
baseurl = 'https://abelight.agilewarsaw.com'
title = "ABE Light 2025"
canonifyurls = true
theme = "hugo-conference"

[params]
Name = "ABE Light 2025"
Description = "AgileByExample Light 2025"
Date = "6 Kwietnia (Niedziela)"
startDate = "2025-04-06T13:45"
Venue = "Akademia Leona Koźmińskiego"
Address = "ul. Jagiellońska 57/59"
City = "Warsaw"
AddressRemarks = "Aula…"
Images = [ "/img/ABElight-ikonka.png" ]
Sections = [
  "about",
  "location",
  "speakers",
  "schedule",
  "partners",
  "sponsors",
  "media",
  "orgs",
  "previous"
]


##########################
#   Link do rejestracji
##########################

[params.CallToAction]
text = "Zarejestruj się (gratis)"
link = "register"


##########################
#   Tytuły sekcji 
##########################

[params.Titles]
about = "O konferencji"
location = "Gdzie?"
speakers = "Kto?"
schedule = "Rozkład jazdy"
sponsors = "Sponsorzy"
partners = "Partnerzy"
media = "Partnerzy medialni"
orgs = "Organizatorzy"
contact = "Kontakt"
previous = "Poprzednie edycje"


####################################
#  Linki do poprzednich edycji
####################################

[[params.Previous]]
name = "2013"
url = 'https://agilewarsaw.com/events/55/'

[[params.Previous]]
name = "2014"
url = 'https://agilewarsaw.com/events/78/'

[[params.Previous]]
name = "2015"
url = 'https://agilewarsaw.com/events/98/'

[[params.Previous]]
name = "2016"
url = 'https://agilewarsaw.com/events/115/'

[[params.Previous]]
name = "2017"
url = 'https://agilewarsaw.com/events/130/'

[[params.Previous]]
name = "2018"
url = 'https://agilewarsaw.com/events/150/'

[[params.Previous]]
name = "2019"
url = 'https://agilewarsaw.com/events/179/'

[[params.Previous]]
name = "2020"
url = 'https://agilewarsaw.com/events/198/'

[[params.Previous]]
name = "2021"
url = 'https://agilewarsaw.com/events/228/'

[[params.Previous]]
name = "2022"
url = 'https://agilewarsaw.com/events/252/'

[[params.Previous]]
name = "2023"
url = 'https://agilewarsaw.com/events/267/'

[[params.Previous]]
name = "2024"
url = 'https://agilewarsaw.com/events/292/'


####################################
#  Sponsorzy
####################################

[[params.Sponsors]]
name = "Akademia Leona Koźmińskiego"
logo = "img/logo_ALK.png"
url = 'https://www.kozminski.edu.pl/'


[[params.Sponsors]]
name = "BEC Poland"
logo = "img/logo_bec.png"
url = 'https://www.linkedin.com/company/becpoland/'

####################################
#  Partnerzy
####################################

[[params.Partners]]
name = "Agile Warsaw"
logo = "img/logo_AW.png"
url = "http://agilewarsaw.com"


[[params.Partners]]
name = "NextGen.PM"
logo = "img/logo_NextGenPM.png"
url = 'https://nextgen.pm/'

####################################
#  Media
####################################

# [[params.Media]]
# name = "Agile Polska"
# logo = "img/logo_APL.png"
# url = "http://agilepolska.pl/"

[[params.Media]]
name = "Kanban przy kawie"
logo = "img/logo_kanban_przy_kawie.png"
url = 'https://kanbanprzykawie.pl/'

# [[params.Media]]
# name = "Agile 247"
# logo = "img/logo_a247.jpg"
# url = "http://www.agile247.pl/"

# [[params.Media]]
# name = "Agile 4U"
# logo = "img/logo_agile4u.png"
# url = 'https://www.meetup.com/agile4u/'

# [[params.Media]]
# name = "LubLean"
# logo = "img/logo_LubLean.png"
# url = 'https://www.meetup.com/LubLean-and-Agile/'

# [[params.Media]]
# name = "Agile Wrocław"
# logo = "img/logo-agile-wroclaw.png"
# url = 'https://www.meetup.com/pl-PL/agilewroclaw/'

# [[params.Media]]
# name = "Agile Poznań"
# logo = "img/logo_agile_poznan.png"
# url = 'https://www.linkedin.com/groups/4406793'

[[params.Media]]
name = "Agile 3M"
logo = "img/logo_agile3m.png"
url = 'https://www.linkedin.com/company/agile3m'

# [params.Media]]
# ame = "Agile Silesia"
# ogo = "img/logo_agile-silesia.png"
# rl = 'https://www.agilesilesia.pl/'

# [params.Media]]
# ame = "ALE Kraków"
# ogo = "img/logo-ale-krakow.png"
# rl = 'https://www.alekrakow.com/'

# [params.Media]]
# ame = "Dare IT"
# ogo = 'img/logo_DareIT.png'
# rl = 'https://www.dareit.io/'

# [params.Media]]
# ame = "Zwinna Łódź"
# ogo = 'img/logo_zwinna_lodz.svg'
# rl = 'https://www.meetup.com/Zwinna-Lodz/'

####################################
#  Organizatorzy
####################################

[[params.Orgs]]
name = "Ania Przybyszewska"
img = "img/org_przybyszewska_2.svg"

[[params.Orgs]]
name = "Ewelina Startek"
img = "img/org_startek_2.svg"

# [params.Orgs]]
# ame = "Ewa Koprowska"
# mg = "img/org_koprowska_2.svg"

[[params.Orgs]]
name = "Piotr Radaj"
img = "img/org_radaj_2.svg"

# [params.Orgs]]
# ame = "Katarzyna Prokopiuk"
# mg = "img/org_prokopiuk_2.svg"

[[params.Orgs]]
name = "Tomek Słowikowski"
img = "img/org_slowikowski_2.svg"

[[params.Orgs]]
name = "Łukasz Szóstek"
img = "img/org_szostek_2.svg"


####################################
#  Rozpiska
####################################

#------------------------
#  Prelegenci
#------------------------

[[params.Schedule]]
name = "Zapisy na warsztaty"
time = "XX:XX"
remark = 'Warto być na czas! Zapisy będą na miejscu i najciekawsze warsztaty zapełnią się najszybciej.'

[[params.Schedule]]
name = "Otwarcie konferencji"
time = "XX:XX"
remark = 'Trochę informacji logistycznych i lecimy z programem…'

#------------------------

[[params.Schedule]]
    [[params.Schedule.authors]]
    name = "Aga Szóstek"
    photo = ""
    bio = "Dr Aga Szóstek jest autorką "Strategii Umami" oraz "Zostań liderem, jakim chcesz!" i ekspertką w zakresie strategii i przywództwa.

Przez ostatnie dwie dekady współpracowała z czołówką firm łączących design, technologię i biznes. Pracowała z takimi markami jak Google, Philips, Samsung, Play, Allegro, EY, Santander, ING, Orange i wieloma innymi, wnosząc do zespołów projektowych i zarządów strategiczne podejście oparte na projektowaniu doświadczeń.

Aga wspiera także swoich klientów w rozwoju liderskim w oparciu o kluczowe wyzwania przywódcze zakotwiczone w ich organizacyjnej kulturze. Oferuje unikatowe programy liderskie dostarczane w formie niezapomnianego doświadczenia."

      [params.Schedule.authors.link]
        href = ''
        text = ''

    [params.Schedule.presentation]
      title = 'Tytuł TBD'
      description = """ Opis TBD """

#------------------------

[[params.Schedule]]
    [[params.Schedule.authors]]
    name = "Kate Hobler"
    photo = ""
    bio = ""

      [params.Schedule.authors.link]
        href = ''
        text = ''

    [params.Schedule.presentation]
      title = 'Tytuł TBD'
      description = """ Opis TBD """

#------------------------

####################################
# Warsztaty
####################################

#-----------------------------------------------------------
# Opis warsztatów w tabelce, dane warsztatodawców są niżej
#-----------------------------------------------------------

[[params.Schedule]]
name = "Warsztaty"
remark = """

 Wszystkie warsztaty będą się toczyły jednocześnie / równolegle czyli możesz dołączyć tylko do jednego z nich.

Zapisy odbędą się na miejscu, przed otwarciem konferencji. Spójrz 👆👆

<br><br>

<strong>Justyna (Kęsik) Rędzikowska
<br> 
Lider(ka) w Świecie Liczb: Jak Komunikować Metryki, by Budować Zaangażowanie
<br>
</strong>
<br>
Czy chcesz lepiej pracować z metrykami i zaangażować w to cały zespół? Czy chcesz opierać swoją pracę na danych i wnieść znaczący wkład w retrospektywy? Wiesz, jak ważne są metryki, ale zawsze trudno było Ci je efektywnie komunikować z zespołem?
<br>
Ten warsztat jest idealny dla Ciebie! :)
<br><br>
Zaczniemy od określenia celu i miejsca naszych działań w życiu zespołu. Omówimy podstawowe metryki procesowe oraz jak o nich rozmawiać z zespołem w sposób, który buduje zaangażowanie i poczucie bezpieczeństwa.
 
<br><br>
Podczas warsztatu dowiesz się:
<ul style=\"padding-left: 0.5em;\">
<li>• Jak efektywnie komunikować metryki, aby zespół czuł się zaangażowany i bezpieczny.</li>
<li>• Jak angażować zespół w pracę z danymi, aby wspólnie dążyć do wzrostu, a nie oceniać ludzi.</li>
<li>• Jak tworzyć kulturę zaufania i otwartości wokół metryk</li>
</ul>
<br>
Zakończymy warsztat analizą rzeczywistych przypadków, najpierw z moich zespołów, a następnie z Twoich, abyś mógł wyjść z gotowymi pomysłami do wdrożenia już następnego dnia.


<br><br>

<strong> Staszek Matczak <br> 
 Jira dla dorosłych - czyli o tym jak można skopać wizualizację pracy i o tym jak można ją naprawić
 <br>
</strong>
<br>
Mamy interesującą sytuację. Z jednej strony jednym z filarów Scruma jest przejrzystość: ,,praca musi być widoczna dla osób ją wykonujących, jak również dla osób, na rzecz których praca ta jest wykonywana''. A z drugiej strony narzędzia, które służą do wizualizacji pracy - takie jak na przykład Jira - są bardzo często przedmiotem żartów, memów i heheszków.
<br><br>
Podczas warsztatu spróbujemy znaleźć odpowiedzi na pytania:
<ul style=\"padding-left: 0.5em;\">
<li>• Po co w ogóle stosujemy narzędzia do planowania i monitorowania pracy? </li>
<li>• Jakie są potrzeby osób które wprowadzają narzędzia oraz osób, które są użytkownikami tych narzędzi? </li>
<li>• Czy możemy pogodzić potrzeby różnych interesariuszy? </li>
<li>• Co może kryć się pod niechęcią do używania narzędzi? </li>
<li>• I czy Jira Admin to nowy Agile Coach?</li>
<br>
Zapraszam osoby, które chcą przyjrzeć się nie tylko warstwie narzędzi i procesów, ale chcą spojrzeć głębiej - na osoby, interakcje, potrzeby oraz strategie realizacji tych potrzeb. Sprawdźmy co można zrobić, żeby narzędzia nam pomagały a nie utrudniały pracę!
<br><br>
Dla pełnej jasności: nie jestem sponsorowany przez Atlassiana i nie jest to prezentacja sprzedażowa. A po drugie: słowo ,,Jira'' w tytule może być zastąpione przez dowolne inne narzędzie do planowania i zarządzania pracą.



<br><br>


<strong> Trener <br> 
 Tytuł warsztatu 
 <br>
</strong>
 Opis warsztatu 2<br>
 cd...
 
"""

#########################
# Impreza 
#########################

[[params.Schedule]]
  name = "Afterparty!"
  time = "~XX:XX"


#---------------------------------------
# Warsztatodawcy -- tylko wizytówki! 
# tematy warsztatów są w rozpisce powyżej
#---------------------------------------

[[params.Schedule]]
workshop = true

  # multiple authors per workshop are OK
  [[params.Schedule.authors]]
  name = "Justyna (Kęsik) Rędzikowska"
  photo = "img/redzikowska.png"
  bio = """
  Specjalizuję się w Ways of Working. Buduję efektywne zespoły, wspierające społeczności, wbijam level up organizacjom. Pracuję z wartościami, ludźmi, danymi i procesami. Uwielbiam się uczyć oraz dzielić wiedzą. 
  <br>
  Od 2003 rozwijam się jako liderka, a od 2006 jako trenerka, facylitatorka i mentorka.
  <br>
  Lubię zadawać pytania, ogromnie ciekawi mnie świat, człowiek i procesy jakie zachodzą pomiędzy.
  <br>
  Aktualnie działam jako Scrum/Kanban Masterka oraz Agile Coachka w Danonie, choć na umowie mi napisano, że jestem Starszym Kierownikiem, a ja ani stara ani panowie pod Żabką nie mówią mi "Kierowniczko" ;)
  """
    [params.Schedule.authors.link]
      text = 'LinkedIn'
      href = 'https://www.linkedin.com/in/justyna-redzikowska/'


[[params.Schedule]]
workshop = true

  # multiple authors per workshop are OK
  [[params.Schedule.authors]]
  name = "Staszek Matczak"
  photo = "img/matczak.jpg"
  bio = """
  Po studiach niespodziewanie okazało się, że trzeba zarabiać na życie – więc poszedłem do pracy.
Zaczynałem od pisania kodu. Ponieważ w miarę dobrze dogadywałem się z ludźmi, zaproponowano
mi stanowisko kierownika zespołu. Planowałem prace, rozdzielałem zadania, rozwiązywałem
problemy, rozmawiałem z ludźmi… Jednak coraz bardziej czułem, że w naszym IT coś nie gra.
Pracowaliśmy wspólnie z utalentowanymi, zaangażowanymi ludźmi, a mimo to ciągle pojawiały się
opóźnienia, wtopy i porażki.<br> 
Szukając lepszych sposobów pracy odkryłem najpierw Scruma, a potem kolejne metody i koncepcje
zwinne – Kanbana, zbiór metod z M3.0, sposoby skalowania… Wciągnęło mnie to bardzo. Przez jakiś
czas łączyłem rolę menedżera zespołu i Scrum Mastera, potem menedżera zespołu i Product Ownera,
aż wreszcie porzuciłem zarządzanie i skupiłem się na wdrażaniu metod zwinnych.
Czego się nauczyłem? Że metody zwinne są proste do zrozumienia, ale trudne do zastosowania. Że
organizacje brawurowo walczą z problemami, które same sobie stwarzają. Że warto jest
niestrudzenie zadawać pytanie „dlaczego?”. Że często chęć zmiany jest powierzchowna. Że nie
zawsze Scrum jest dobrym rozwiązaniem problemu. Że wszystko opiera się na wartościach.
Jestem ojcem trójki wspaniałych dzieci, współorganizatorem trójmiejskiej społeczności Agile3M.
Kiedyś pisałem coś na blogu www.trzeciakawa.pl 
  """
    [params.Schedule.authors.link]
      text = 'LinkedIn'
      href = 'https://www.linkedin.com/in/staszekmatczak/'



#[[params.Schedule]]
#workshop = true
#
  ## multiple authors per workshop are OK
  #[[params.Schedule.authors]]
  #name = ""
  #photo = ""
  #bio = """
  #"""
    #[params.Schedule.authors.link]
      #text = ''
      #href = ''
#------------------------
