publishDir = "docs"
baseurl = "https://abelight.agilewarsaw.com"
title = "ABE Light 2024"
canonifyurls = true
theme = "hugo-conference"

[params]
Name = "ABE Light 2024"
Description = "AgileByExample Light 2024"
Date = "10 Marca (Niedziela)"
startDate = "2024-03-10T13:45"
Venue = "Akademia Leona Koźmińskiego"
Address = "ul. Jagiellońska 57/59"
City = "Warsaw"
AddressRemarks = "Aula…"
Images = [ "/img/ABElight-ikonka.png" ]
Sections = [
  "about",
  "location",
  "speakers",
  "schedule",
  "partners",
  "sponsors",
  "media",
  "orgs",
  "previous"
]


##########################
#   Link do rejestracji
##########################

[params.CallToAction]
text = "Zarejestruj się (gratis)"
link = "register"


##########################
#   Tytuły sekcji 
##########################

[params.Titles]
about = "O konferencji"
location = "Gdzie?"
speakers = "Kto?"
schedule = "Rozkład jazdy"
sponsors = "Sponsorzy"
partners = "Partnerzy"
media = "Partnerzy medialni"
orgs = "Organizatorzy"
contact = "Kontakt"
previous = "Poprzednie edycje"


####################################
#  Linki do poprzednich edycji
####################################

[[params.Previous]]
name = "2013"
url = "https://agilewarsaw.com/events/55/"

[[params.Previous]]
name = "2014"
url = "https://agilewarsaw.com/events/78/"

[[params.Previous]]
name = "2015"
url = "https://agilewarsaw.com/events/98/"

[[params.Previous]]
name = "2016"
url = "https://agilewarsaw.com/events/115/"

[[params.Previous]]
name = "2017"
url = "https://agilewarsaw.com/events/130/"

[[params.Previous]]
name = "2018"
url = "https://agilewarsaw.com/events/150/"

[[params.Previous]]
name = "2019"
url = "https://agilewarsaw.com/events/179/"

[[params.Previous]]
name = "2020"
url = "https://agilewarsaw.com/events/198/"

[[params.Previous]]
name = "2021"
url = "https://agilewarsaw.com/events/228/"

[[params.Previous]]
name = "2022"
url = "https://agilewarsaw.com/events/252/"

[[params.Previous]]
name = "2023"
url = "https://agilewarsaw.com/events/267/"


####################################
#  Sponsorzy
####################################

[[params.Sponsors]]
name = "DXC Technology"
logo = "img/logo-DXC.png"
url = "https://dxc.com/pl/en"

[[params.Sponsors]]
name = "ProCognita"
logo = "img/logo_procognita.png"
url = "https://procognita.pl/"

[[params.Sponsors]]
name = "Akademia Leona Koźmińskiego"
logo = "img/logo_ALK.png"
url = "https://www.kozminski.edu.pl/"

####################################
#  Partnerzy
####################################

[[params.Partners]]
name = "Agile Warsaw"
logo = "img/logo_AW.png"
url = "http://agilewarsaw.com"


[[params.Partners]]
name = "NextGen.PM"
logo = "img/logo_NextGenPM.png"
url = "https://nextgen.pm/"

####################################
#  Media
####################################

[[params.Media]]
name = "Agile Polska"
logo = "img/logo_APL.png"
url = "http://agilepolska.pl/"

# [[params.Media]]
# name = "Agile 247"
# logo = "img/logo_a247.jpg"
# url = "http://www.agile247.pl/"

# [[params.Media]]
# name = "Agile 4U"
# logo = "img/logo_agile4u.png"
# url = "https://www.meetup.com/agile4u/"

# [[params.Media]]
# name = "LubLean"
# logo = "img/logo_LubLean.png"
# url = "https://www.meetup.com/LubLean-and-Agile/"

# [[params.Media]]
# name = "Agile Silesia"
# logo = "img/logo_agile-silesia.png"
# url = "https://www.agilesilesia.pl/"

[[params.Media]]
name = "Kanban przy kawie"
logo = "img/logo_kanban_przy_kawie.png"
url = "https://kanbanprzykawie.pl/"

# [[params.Media]]
# name = "Agile Wrocław"
# logo = "img/logo-agile-wroclaw.png"
# url = "https://www.meetup.com/pl-PL/agilewroclaw/"

# [[params.Media]]
# name = "ALE Kraków"
# logo = "img/logo-ale-krakow.png"
# url = "https://www.alekrakow.com/"

####################################
#  Organizatorzy
####################################

[[params.Orgs]]
name = "Ania Przybyszewska"
img = "img/org_przybyszewska_2.svg"

[[params.Orgs]]
name = "Ewelina Startek"
img = "img/org_startek_2.svg"

[[params.Orgs]]
name = "Ewa Koprowska"
img = "img/org_koprowska_2.svg"

[[params.Orgs]]
name = "Piotr Radaj"
img = "img/org_radaj_2.svg"

[[params.Orgs]]
name = "Łukasz Szóstek"
img = "img/org_szostek_2.svg"

[[params.Orgs]]
name = "Katarzyna Prokopiuk"
img = "img/org_prokopiuk_2.svg"

[[params.Orgs]]
name = "Tomek Słowikowski"
img = "img/org_slowikowski_2.svg"


####################################
#  Rozpiska
####################################

#------------------------
#  Prelegenci
#------------------------

[[params.Schedule]]
name = "Zapisy na warsztaty"
time = "po południu"
remark = 'Warto być na czas! Zapisy będą na miejscu i najciekawsze warsztaty zapełnią się najszybciej.'

[[params.Schedule]]
name = "Otwarcie"
remark = 'Trochę informacji logistycznych i lecimy z programem…'


[[params.Schedule]]
    [[params.Schedule.authors]]
    name = "Tomasz Wykowski"
    photo = "img/TWykowski_2022.png"
    bio = "Od ponad dwóch dekad uczestniczę w tworzeniu produktów software'owych, a od ponad piętnastu lat dzielę się swoją wiedzą poprzez szkolenia i konsulting. Jestem jedynym polskim Certified Scrum Trainer, CST akredytowanym przez Scrum Alliance oraz jednym z dwóch polskich Certified LeSS Coach. W przerwach pomiędzy pracą z liderami różnych firm piszę artykuły i nagrywam podcasty, które znajdziesz na stronie ProCognity. Jestem autorem książki \"Biznes Odczarowany. Scrum: jak osiągać cele, gdy wszystko się zmienia?\", w której opowiadam jak uniknąć iluzji nierealnych planów i stworzyć zwinną firmę."

      [params.Schedule.authors.link]
        href = "https://www.linkedin.com/in/wykowski/"
        text = "LinkedIn"

    [params.Schedule.presentation]
      title = 'TBD'
      description ='TBD'
#------------------------

[[params.Schedule]]
    [[params.Schedule.authors]]
    name = "Kuba Szczepanik"
    photo = "img/szczepanik.jpg"
    bio = """
    Pomagam przejść przez zmianę firmom, które chcą wykorzystać potencjał tkwiący w zwinności.<br>
     Jestem konsultantem, mentorem i trenerem, specjalizującym się w temacie zwinnych transformacji dużych organizacji. Wspieram bezpośrednio zespoły projektowe rozwijające swoje produkty i pomagam wyjść z podejściem zwinnym do kręgów „biznesowych” w firmach. <br>
     Moją misją jest propagowanie porządnej zwinności w zespołach i firmach oraz przeciwstawienie się płytkim zmianom oraz stosowania Agile-In-The-Name-Only. <br>
     Jestem współautorem portalu <a href="https://agile247.pl">agile247.pl</a> i podcastu „Porządny Agile”, piszę też na swoim blogu kubaszczepanik.pl i szykuję książkę o zwinnych transformacjach – więcej informacji na stronie <a href="https://zwinneorganizacje.pl">zwinneorganizacje.pl</a>.
    """

    [params.Schedule.authors.link]
      href = "https://www.kubaszczepanik.pl/"
      text = "kubaszczepanik.pl"

    [params.Schedule.presentation]
      title = 'Jak Scrum Master może wesprzeć efektywność zespołu?'
      description ="""
      Efektywność zespołów to temat bardzo istotny biznesowo i jednocześnie traktowany dość po macoszemu w wielu firmach. Nie jest to łatwe – rodzi pytania jak ją mierzyć, kto ma na nią wpływ i jak ją poprawić. <br>
      Na bazie doświadczeń w pracy z organizacjami przedstawię moja propozycję planu działania dla Scrum Mastera, który chce przejąć inicjatywę i uruchomić działania związane z podwyższeniem efektywności. Pokażę też model do auto-refleksji dla Scrum Mastera – jakie kompetencje są potrzebne, żeby realnie wpłynąć na omawiany temat.
      """
#------------------------

[[params.Schedule]]
    [[params.Schedule.authors]]
    name = "Agnieszka Cieślawska"
    photo = ""
    bio = ""

      # [params.Schedule.authors.link]
      #   href = ""
      #   text = ""

    [params.Schedule.presentation]
      title = 'TBD'
      description ='TBD'

####################################
# Warsztaty
####################################

#-----------------------------------------------------------
# Opis warsztatów w tabelce, dane warsztatodawców są niżej
#-----------------------------------------------------------

[[params.Schedule]]
name = "Warsztaty"
remark = """

Wszystkie warsztaty będą się toczyły jednocześnie / równolegle czyli możesz dołączyć tylko do jednego z nich.

Zapisy odbędą się na miejscu, przed otwarciem konferencji. Spójrz 👆👆

<br><br>

<strong>Ewa Koprowska</strong><br>
TBD
<br><br>


<strong>Joanna Płaskonka</strong><br>
TBD


<br><br>

<strong>Agata Kabat <br> 
Mózg w coachingu, czyli praktyczna opowieść o procesie zmiany</strong>
<br><br>
Chciałabym Was zaprosić do odkrycia klasycznego coachingu (zgodnego z definicją ICF) na nowo, tym razem z perspektywy naukowej dotyczącej funkcjonowania ludzkiego mózgu w kontekście procesu zmiany i relacji międzyludzkich. Będzie to okazja m.in. do przyjrzenia się źródłom potencjalnego oporu, którego nierzadko doświadczamy jako agenci zmiany we współpracy z zespołami, jednostkami czy organizacjami. Co więcej, wspólnie dowiemy się jak pracować z takimi wyzwaniami wykorzystując podstawową strukturę rozmowy coachingowej oraz model SCARF w ćwiczeniach. <br>
Dodatkowy bonus: jeżeli zależy Ci na rozwoju własnych procesów decyzyjnych czy zmianie nawyków, z powodzeniem zastosujesz poznane narzędzia w ramach indywidualnych refleksji. <br>
Na warsztaty przygotujcie proszę przykład problemu lub dylematu, z którym się mierzycie i chcielibyście się nim podzielić w grupie. Wykorzystamy je w praktyce. Nasze kory przedczołowe na pewno się ucieszą :) 


<br><br>

<strong>Tomek Serafin i Jakub Dobosz<br>
Symulacja Scruma: obraz czy 1000 słów?
</strong><br>

Z przewodnika po Scrumie: Scrum to "uproszczone ramy postępowania, które pomagają […] wytwarzać wartość poprzez adaptacyjne rozwiązywanie złożonych problemów". <br>
Czy przewodnik po Scrumie jest tak prosty jak to możliwe? Jak dobrze rozumiemy podstawowe elementy metody i do jakiego stopnia nasze rozumienie jest zgodne z rozumieniem innych? Czy potrafimy wyjaśnić Scruma innym nie używając trudnych słów? <br>
Na te i inne pytania odpowiemy sobie w trakcie warsztatu, w trakcie którego będziemy wytwarzać wartość (zrozumienie Scruma) przez adaptacyjne rozwiązywanie złożonego problemu (jak to zrobić dobrze?) - wyjaśnijmy Scruma pracując Scrumem!


<br><br>

<strong>Adrian Janik i Mateusz Hauk</strong><br>
TBD


<br><br>

<strong>Tomek Wykowski</strong><br>
TBD


<br><br>

<strong>Krzysztof Niewiński</strong><br>
TBD


<br><br>

<strong>Justyna Wykowska i Karolina Karbarz</strong><br>
TBD


<br><br>

<strong>Magda Gałaj i Marcin Gałaj</strong><br>
TBD


<br><br>

<strong>Jaga Biernacka</strong><br>
TBD

"""

#########################
# Impreza 
#########################

[[params.Schedule]]
  name = "Afterparty!"
  time = "~19:00"


#---------------------------------------
# Warsztatodawcy -- tylko wizytówki! 
# tematy warsztatów są w rozpisce powyżej
#---------------------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Ewa Koprowska"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    #   href = ""
    #   text = ""

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Joanna Płaskonka"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    #   href = ""
    #   text = ""

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Agata Kabat"
  photo = "img/Agata_Kabat.jpg"
  bio = """
  Od 8 lat jestem związana z zarządzaniem projektami, wspieram tworzenie produktów oraz usług, a także ulepszam procesy w sektorach: BPO/SSC, consulting, fintech oraz IT. Pracowałam jako Project Managerka, Team Liderka, Scrum Masterka, aktualnie działam w roli Agile Coachki. <br>
  Dodatkowo, jako coachka w trakcie akredytacji ICF, specjalizuję się w pracy coachingowej z liderami, zespołami oraz Scrum Masterami/Agile Coachami używając m.in. techniki Brain-Based Coaching. <br>
  W wolnych chwilach ćwiczę boks, praktykuję jogę i uważnie spaceruję po lesie.
  """
    # [params.Schedule.authors.link]
    #   href = ""
    #   text = ""

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Tomek Serafin"
  photo = "img/serafin.jpg"
  bio = """
Zaczynałem karierę zawodową jako programista, następnie tworzyłem i dostarczałem wartość jako analityk, menadżer projektu, menadżer produktu, lider zespołu, Scrum Master, a nawet Head of HR. <br>
Obecnie jestem programistą i przywódcą służebnym zespołu Scrumowego. Jednym z moich hobby jest tworzenie oraz prowadzenie warsztatów wzmacniających zrozumienie zwinności. Lubię zrozumienie.
  """
  [params.Schedule.authors.link]
    href = 'https://www.linkedin.com/in/tpserafin/'
    text = "LinkedIn"

  [[params.Schedule.authors]]
  name = "Jakub Dobosz"
  photo = "img/dobosz.jpg"
  bio = """
Cenię synergię zespołu, przejrzystość i skuteczną komunikację. Skupiam się na wartości biznesowej i szukaniu sposobów na jej optymalne dostarczanie. Wierzę, że poprzez ciągłe zwiększanie naszego zrozumienia własnych potrzeb i motywacji jesteśmy w stanie tworzyć wyjątkowe rozwiązania. Jednym z moich celów jest budowanie środowisk, gdzie każdy ma poczucie własności i możliwość wpływania na nie. Praktykuję NVC i zwiększanie swojej uważności.
  """
   [params.Schedule.authors.link]
    href = 'https://www.linkedin.com/in/jakubdobosz/'
    text = "LinkedIn"

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Adrian Janik"
  photo = "img/janik.jpg"
  bio = """
  Od 15 lat zajmuję się szkoleniem, rozwijaniem kompetencji miękkich. Od 5 lat odkrywam świat zwinnych zespołów i przynoszę do niego narzędzia i rozwiązania wzmacniające zespołowość, samoorganizację oraz współodpowiedzialność.  Wspieram organizacje w planowaniu i skutecznym wdrażaniu zmian, dostarczam wiedzę i umiejętności związane z kompetencjami osobistymi, komunikacją oraz zespołowością. Pomagam liderom i członkom zespołów skutecznie pełnić ich role, a przez to budować samodzielne i odpowiedzialne teamy. <br>
  Jako trener i psycholog głęboko wierzę, że dobre relacje są nie tylko kluczem do sukcesu zespołów i organizacji, ale też źródłem dobrego i pełnego życia. <br>
  Prywatnie podróżuję i biegam, a później odpoczywam z książką w ręku.
  """
    # [params.Schedule.authors.link]
    # href = ""
    # text = ""

  [[params.Schedule.authors]]
  name = "Mateusz Hauk"
  photo = "img/hauk.jpg"
  bio = """
  Trener biznesu od 2005 roku. Certyfikowany Scrum Master.  <br>
  W działaniach rozwojowych propaguje ideę „Zarządzania z ludzką twarzą”. Wspiera zespoły samoorganizujące (agile). Współautor wielu dedykowanych programów rozwojowych dla liderów i menedżerów, koordynator metodologiczny i trener wiodący akademii menedżerskich. Współautor koncepcji i koordynator merytoryczny projektów związanych z tworzeniem platform e-learningowych i e-coachingowych <br>
  Realizuje szkolenia z zakresu: <br>
  • Umiejętności szefowskich i menedżerskich <br>
  • Komunikacji i asertywności <br>
  • Budowania i usprawniania pracy zespołów <br>
  • Facylitacji i moderacji <br>
  • Budowania i usprawniania relacji w miejscu pracy <br>
  • Skuteczności osobistej (kapitał psychologiczny i społeczny) <br>
  • Wdrażania i wzmacniania zmian <br>
  • Wykorzystywania agile w biznesie """
    # [params.Schedule.authors.link]
    # href = ""
    # text = ""

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Krzysztof Niewiński"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    #   href = ""
    #   text = ""

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Justyna Wykowska"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    # href = ""
    # text = ""

  # [[params.Schedule.authors]]
  # name = "Karolina Karbarz"
  # photo = ""
  # bio = ""
    # [params.Schedule.authors.link]
    # href = ""
    # text = ""

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Magda Gałaj"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    # href = ""
    # text = ""

  [[params.Schedule.authors]]
  name = "Marcin Gałaj"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    # href = ""
    # text = ""

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Jaga Biernacka"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    #   href = ""
    #   text = ""

#------------------------