publishDir: docs
baseurl: "https://abelight.agilewarsaw.com"
title: "ABE Light 2020"
canonifyurls: true
theme: "hugo-conference"

#GoogleAnalytics: "UA-112461830-1"

params:
  # Conference info
  Name: "ABE Light 2021"
  Description: "AgileByExample Light 2021"
  Date: "10 April (Saturday)"
  startDate: "2021-04-10T13:45"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Online"
  #Address: "Stokłosy 3"
  #City:  "Warszawa"
  #State: "Quintana"
  Images: ["/img/ABElight-ikonka.png"]

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    #- location
    - speakers
    - schedule
    - partners
    - sponsors
    #- media
    - orgs
    - previous
      #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About the conference"
    location: "Where?"
    speakers: "Who?"
    schedule: "Timetable"
    sponsors: "Sponsors"
    partners: "Partners"
    media: "Media Partners"
    orgs: "Organizers"
    contact: "Contact"
    previous: "Previous Editions"

  Previous:
    - name: "2013"
      url: "https://agilewarsaw.com/events/55/"
    - name: "2014"
      url: "https://agilewarsaw.com/events/78/"
    - name: "2015"
      url: "https://agilewarsaw.com/events/98/"
    - name: "2016"
      url: "https://agilewarsaw.com/events/115/"
    - name: "2017"
      url: "https://agilewarsaw.com/events/130/"
    - name: "2018"
      url: "https://agilewarsaw.com/events/150/"
    - name: "2019"
      url: "https://agilewarsaw.com/events/179/"
    - name: "2020"
      url: "https://agilewarsaw.com/events/198/"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
      text: "Free Registration"
      link: "register"
      #text: "Zarejestruj się gratis"
      #link: "register"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "KMD"
      logo: "img/logo_kmd.png"
      url: "https://career.kmd.net/join-kmd-poland"

    - name: "ProCognita"
      logo: "img/logo_procognita.png"
      url: "https://procognita.pl/"

      #  - name: "Vistula"
      #    logo: "img/logo_vistula.jpg"
      #    url: "http://www.vistula.edu.pl/"

    - name: "Slido"
      logo: "img/logo_slido.png"
      url: "http://www.slido.com"

  # List of Partners
  Partners:
    - name: "Agile Warsaw"
      logo: "img/logo_AW.png"
      url: "http://agilewarsaw.com"

      # - name: "PKO BP"
      #   logo: "img/logo_PKOBP.jpg"
      #   url: "https://www.pkobp.pl"

      #- name: "PMI Oddział Warszawa"
      #logo: "img/logo_PMI.png"
      #url: "http://pmi.org.pl/pmi/oddzialy/warszawa/"

  # List of Media Partners
  Media:
    - name: "Agile Polska"
      logo: "img/logo_APL.png" 
      url: "http://agilepolska.pl/"

    - name: "Agile 247"
      logo: "img/logo_a247.jpg" 
      url: "http://www.agile247.pl/"

  Orgs:
    - name: "Piotr Radaj"
      img: "img/org_radaj.png"
    - name: "Ania Przybyszewska"
      img: "img/org_przybyszewska.png"
    - name: "Łukasz Przezorski"
      img: "img/org_przezorski.png"
    - name: "Kinga Grabowska"
      img: "img/org_kinga.png"
    - name: "Mateusz Srebrny"
      img: "img/org_srebrny.png"
    # - name: "Magdalena Walczak"
    #img: "img/org_walczak.png"
    - name: "Łukasz Szóstek"
      img: "img/org_szostek.png"
    #- name: "Michał Koprowski"
      #img: "img/org_koprowski.png"
      #- name: "Piotr Szczygieł"
      #img: "img/org_szczygiel.png"

  # The entire schedule
  Schedule:
    - name: "Opening"
      time: "13h45"
      remark: "Please, be on time!<br>This is where you will be signing-up for workshops."

    - name: "Workshops"
      time: "14h15"
      remark: "There will be X parallel workshops.<br>
      Workshop languages are mentioned in descriptions.<br><br>
      
      <strong>Bożena Andrzejak<br>
      Konflikt czy zwykłe nieporozumienie, jak rozpoznać nadchodzący konflikt?</strong>
      <img class=\"icon-lang\" src=\"img/lang-pl.svg\"> <br>
      Stara zasada medyczna mówi, że lepiej zapobiegać niż leczyć. Nie jestem zwolenniczką zarządzania przez konflikt, więc przekładam tę zasadę również na obszar komunikacji międzyludzkiej. Różnorodność, różnica zdań i perspektyw, nawet nieporozumienie, mogę być źródłem kreatywnych rozwiązań. Ale gorący konflikt prawie zawsze jest niszczący.<br>
      Dlatego lepiej rozpoznać jego pierwsze objawy i interweniować zanim będzie za późno. Podczas naszego spotkania przyjrzymy się jak zwykła sytuacja może eskalować w konflikt i co leży u źródeł takiego rozwoju sytuacji. Kiedy rozumiemy powody, mamy szansę na to, aby zatrzymać się w porę i zrobić krok do tyłu zanim wpadniemy w wir niszczącego procesu.<br><br>
              
      <strong>Justyna Wykowska<br>
      Szkiełko i oko czyli dylematy biznes analityka</strong>
      <img class=\"icon-lang\" src=\"img/lang-pl.svg\"><br>
      \"Jeśli nie umiesz zmierzyć rezultatu zmian to nic nie zmieniaj\". Podstawą pracy PO i analityka biznesowego jest mierzenie rezultatów zmian w produkcie. Zapraszam na warsztat gdzie na przykładach produktów dotkniemy tematu metryk i wskaźników. Sprawdzimy co i kiedy warto mierzyć, kiedy metryka przynosi nam oczekiwane korzyści a kiedy jest szkodliwa i zdefiniujemy metryki dla naszych przykładów.<br><br>

      <strong>Jurgen de Smet<br>
      Agile is not Scrum and Scrum is not necessarily Agile</strong>
      <img class=\"icon-lang\" src=\"img/lang-gb.svg\"><br>
      Today, bad or zombie Scrum is the biggest enemy of Scrum and not waterfall or phase gate projects and programs. In this workshop we're going to explore your understanding of Scrum and provide insights on how to bring Scrum to a higher level of Agility. Enabling you and your teams creativity towards experimentation and innovation beyond the retrospective into the Products you build.<br><br>

      <strong>Maciej Sowiński<br>
      Myślenie systemowe dla Agile Coachów Light</strong>
      <img class=\"icon-lang\" src=\"img/lang-pl.svg\"><br>
      Workshop 2<br><br>
      
      <strong>Workshop EN</strong>
      <img class=\"icon-lang\" src=\"img/lang-gb.svg\"><br>
      Workshop 1 desc <br><br>
              
      <strong>Workshop PL</strong>
      <img class=\"icon-lang\" src=\"img/lang-pl.svg\"><br>
      Workshop 2<br><br>
      "

      # PANEL
    - authors:
        - name: "Panelist 1"
          photo: "img/ABElight-ikonka-square_300.png"
          bio: "panelist 1 bio"
          link:
            href: "https://agilewarsaw.com"
            text: "LinkedIn/www?"
        - name: "Panelist 2"
          photo: "img/ABElight-ikonka-square_300.png"
          bio: "panelist 2 bio"
          link:
            href: "https://agilewarsaw.com"
            text: "LinkedIn/www?"
      presentation:
        title: "Panel title"
        description: "panel description..."
        time: "16h00"
      weight: 10

    - authors:
        - name: "Angela Johnson" 
          photo: "img/ABElight-ikonka-square_300.png"
          bio: "Angela is a Certified Scrum Trainer (CST) and Certified Less Practitioner (CLP) and Training from the BACK of the Room (TBR) Certified Trainer and one of the first Scrum Alliance Path to CSP Approved Educators. Angela helps others successfully implement Scrum and Agile to achieve their goals and objectives.<br> Clients that Angela has transformed include: agency / services, software, hardware, marketing, learning and development and more. The breadth and depth of her experience extends beyond Scrum and includes Kanban, eXtreme Programming, Facilitation and Organizational Change for business agility.<br> A graduate of Hamline University (B.A.) and the University of St. Thomas (M.B.C.), Angela focuses her work on the upper Midwestern areas of the United States to best serve in her most important roles: wife and mom.
"
          link:
            href: "https://agilewarsaw.com"
            text: www
      presentation:
        title: "Is Product the New Misused Agile Term?"
        description: "When you hear “product” or “product owner” what comes to mind in your context? A temporary project? A project manager? If you were to ask the customers who pay your company money what they think your product is would it be the same definition that you came up with?<br> In this session we will discuss how the term product is being misused in the Agile community. We’ll also explore techniques such as broadening questions and narrowing questions that can help your organization figure out just where to start with an Agile approach such as Scrum. These techniques can help set up your Scrum adoption for success and avoid creating confusion with misunderstood terms."
        time: "17h00"
      weight: 100


    - name: "Closing"
      time: "18h00"
      remark: ""

    #- name: "Lunch"
      #remark: "You will have to take care of your own lunch. There are restauriants in the neighbourhood."



     ###########################
     ###  WORKSHOP TRAINERS  ###
     ###########################
    - authors:
      - name: "Bożena Andrzejak"
        photo: "img/ABElight-ikonka-square_300.png"
        bio: "Facilitator, consultant, coach and therapist. Bożena empowering her clients to explore their natural resources thus creating space to discover and experiment new, effective behaviors. Especially to help to identify and resolve internal and external conflicts.<br> She takes active part as a guest speaker or coach in events as: Scrum Days, Agile By Example, ACCP, Uncof, Management 3.0, Novotalk. She is an author of soft skills training programmes dedicated to agile team members.  "
        link:
          href: "https://"
          text: "www"
      workshop: true

    - authors:
      - name: "Justyna Wykowska"
        photo: "img/JustynaWykowska.png"
        bio: "Kim jestem? Inżynierem automatykiem, programistą, managerem, Product Ownerem, Scrum Masterem, trenerem, coachem personalnym, specjalistą od Agile... I nie przestaję się uczyć nowych rzeczy.<br>Pomogę Ci wykorzystać Twoje mocne strony. Podpowiem, jak osiągnąć zamierzony cel. Kiedy jestem z zespołem dbam, aby grupa dobrze się czuła, i co najważniejsze była efektywna. Zbudowałam już ponad 20 fantastycznych zespołów, pracując z nimi jako lider lub coach."
        link:
          href: "https://"
          text: "www"
      workshop: true

    - authors:
      - name: "Jurgen De Smet"
        photo: "img/jurgenDeSmet.jpg"
        bio: "Jurgen De Smet ma dar ulepszania procesów operacyjnych poprzez zastosowanie koncepcji gier w środowisku poważnych organizacji. Jako lider zmiany w jednej z największych transformacji Agile w europejskiej służbie zdrowia, przekształcał firmy w najbardziej regulowanych prawnie i unikających ryzyka branżach i sprawił, że osiągnęły wspaniałe wyniki w zakresie innowacji. Jego wprowadzenie do Agile i Lean sprawia, że organizacje na wszystkich szczeblach zarządzania szybko odkrywają wartość z nowego podejścia i wkrótce nie są w stanie wyobrazić sobie pracy w jakikolwiek inny sposób."
        link:
          href: "https://"
          text: "www"
      workshop: true

        #    - authors:
        #        - name: "Tomasz Wykowski"
        #          photo: "img/TomekWykowski.png"
        #          bio: "“We learn thru all our life, therefore learning needs to be fun.”<br>
        #          As an Agile Coach and Trainer, Tomasz supports individuals and organizations in their quest for Agility, better results and amazing workplace. He's the first Polish Certified Scrum Trainer and LeSS-Friendly Scrum Trainer. He understands the needs of young companies and helps them succeed in their markets.<br>
        #Tomasz holds a Master's Degree in Automatic and Robotic and has a broad experience in software development from different perspectives, including engineering, quality assurance, project management and Agile Coaching. In 2010 he founded ProCognita, a training and consulting company."
        #          link:
        #              href: "https://procognita.com/company/team/trainers/tomasz-wykowski/"
        #              text: "www"
        #      workshop: true
        #
        #    - authors:
        #        - name: "Justyna Wykowska"
        #          photo: "img/JustynaWykowska.png"
        #          bio: "“Behind every product, there are people who are creating it.”<br>
        #An engineer, software developer, manager, Product Owner, Scrum Master, trainer, personal coach, and Agile specialist. By combining a technical degree with soft skills education and real-life experience, Justyna emphasizes the collaboration and communication factors in organizations and teams' dynamics.<br>
        #For almost a decade Justyna has led diverse multinational and distributed teams involved in huge projects. Since 2014 she is working with ProCognita as an Agile Coach and Trainer, supporting companies from many business sectors including customer support, software and hardware development."
        #          link:
        #              href: "https://procognita.com/company/team/trainers/justyna-wykowska/"
        #              text: "www"
        #      workshop: true
        #
        #    - authors:
        #        - name: "Mariusz Petlic"
        #          photo: "img/MariuszPetlic.png"
        #          bio: "“The quality of the product is created by the quality of the process.”<br>
        #          I am fascinated by the quality of the product and the process. I would like to help you refine your product so that customers are satisfied and recommend it to others. That is why it is important to constantly improve the process of creating a product. If you do not want to spend money on activities that may end in failure, we can find together the best models for creating new products and developing existing ones.<br>
        #I worked with companies: ComputerLand, Systemy Kodów Kreskowych, Hurra.com, eSky.pl. As an active Scrum Master, I supported and built teams. Now I'm an Agile Coach. At work with major companies I have learned how to test products and I will gladly share this knowledge with you."
        #          link:
        #              href: "https://procognita.com/company/team/trainers/mariusz-petlic/"
        #              text: "www"
        #      workshop: true




    #####################
    ##     TEMPLATE    ##
    #####################
      # DWÓCH PRELEGENTÓW WYGLĄDA TAK:
      #    - authors:
      #        - name: "Hanna Kaczyńska"
      #          photo: "img/kaczynska.jpg"
      #          bio: "W PKO BP od 10 lat. Początki to obsługa klienta i sprzedaż, od 7 lat zajmuję się projektowaniem i prowadzeniem szkoleń w banku. Ponad rok temu zetknęłam się po raz pierwszy ze zwinnością, dziś sama nią zarażam jako Scrum Master i jako trener prowadzący szkolenia dla organizacji. Uwielbiam pracę z ludźmi i dla ludzi."
      #          link:
      #            href: "https://pl.linkedin.com/in/hanna-kaczyńska-508960142"
      #            text: "LinkedIn"
      #        - name: "Karol Krawiec"
      #          photo: "img/krawiec.jpg"
      #          bio: "Z sektorem bankowym związany od 15 lat, zaczynał swoje doświadczenie jako programista COBOL i konsultant w tworzeniu centralnego systemu bankowego. Kierował różnorodnymi projektami i programami IT dot. rozwoju produktów i usług bankowych, zarządzał zespołem Kierowników Projektów. Zainspirowany dążeniem ku zwinności, z pasją adaptuje podejście Agile – najpierw w zespołach IT, obecnie w ramach Transformacji Cyfrowej w skali całej Organizacji. Scrum Master, Product Owner i wyznawca idei ‘Da Się’."
      #          link:
      #            href: "https://pl.linkedin.com/in/karolkrawiec"
      #            text: "LinkedIn"
      #      presentation:
      #        title: "Dlaczego (czasem) warto zdjąć miarę u krawca?"
      #        description: "Rynek szkoleń pełen jest gotowych rozwiązań, które pozwalają zdobywać czy rozwijać potrzebne w organizacji kompetencje. Trudno jednak w komercyjnych propozycjach znaleźć zgrabny pakiet uszyty na miarę dla konkretnej firmy. Ustalone pół roku wcześniej z firmą szkoleniową programy szybko się dezaktualizują i nie zawsze elastycznie się negocjują. Kiedy do tego wszystkiego dodamy nowe w organizacji role: Product Owner i Scrum Master oraz założymy, że organizacja chce inwestować w ich rozwój - zapotrzebowanie ilościowe i jakościowe na różne szkolenia rośnie...
      #Jak firma może poradzić sobie z tym wyzwaniem? I dlaczego, zamiast kupować gotowe ubrania ze sklepowych wieszaków, czasem warto mieć firmowego krawca, który zawsze zdejmie z nas właściwą miarę?<br>Zapraszamy do wysłuchania opowieści o pewnej Akademii Zwinności…"

