baseURL = "https://agilewarsaw.com/"
languageCode = "en-us"
title = "Agile Warsaw"

theme = ["agilewarsaw"]
buildFuture = true
publishDir = "docs"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = -100

  [[menu.main]]
    identifier = "archive"
    name = "All events"
    url = "/events"
    weight = 1
